services:
  db:
    container_name: sqlserver_db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "8003:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=0.-Remy-.0
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - db_network

  adminer:
    container_name: adminer_ui
    image: adminer:latest
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=db
    depends_on:
      - db
    networks:
      - db_network

volumes:
  sqlserver_data:

networks:
  db_network:
    driver: bridge
